FROM node:16.15.1

RUN mkdir -p /home/Castr/backend

COPY ./ /home/Castr/backend

WORKDIR /home/Castr/backend

RUN npm install

ENV HOST 0.0.0.0
ENV PORT 4350

EXPOSE 4350

CMD ["node", "/home/Castr/backend/index.js"]

# an example to run this on docker
# 1. docker build -t castr .
# 2. docker run -d -p 4350:4350 --name castr castr:latest
