name: actions

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.14.0]
        
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing Nodejs dependencies
        run: npm install
      - name: Run test cases
        run: npm test
